spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=Asia/Kuala_Lumpur
    username: root
    password: dummypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # dev阶段用 update，prod建议改为 validate 或 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: seckill

server:
  port: 8080
