spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=Asia/Kuala_Lumpur
    username: root
    password: dummypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # dev阶段用 update，prod建议改为 validate 或 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: 1000ms
      shutdown-timeout: 100ms

  application:
    name: seckill

server:
  port: 8080

jwt:
  secret: my-jwt-secret-key-my-jwt-secret-key
  expiration: 3600000 # 1小时

